### ISSUE TITLE
return spaces in proper order

### ISSUE THREAD

**Issue by szymonkaliski** [asmagill/hs._asm.undocumented.spaces#1]
Hey, this module is getting better and better!

Would it be possible to get spaces with `query` or ideally with `hs.screen:spaces()` in proper order? On start it's ok, but when I rearrange them, then the order stays the same and it messes up my small widget displaying current space :) 

I just compare space from `hs.screen:spaces()` to `spaces.activeSpace()` while iterating over `hs.screen:spaces()`.

**Comment by szymonkaliski** [comment]
Also, it seems that in `spaces.debug.layout` they are in proper order, so the data is somewhere... If you point me in the right direction I could try submitting a PR, but at this point I'm not sure where to look :)

**Comment by asmagill** [comment]
I suspect that parsing the results of debug.layout will be the solution -- In determining what mask values were useful for the query command, I discovered that there are some values which provide the same data, but in a different order, at least for system spaces (don't recall seeing the user space order changing, but I'll check again -- if so, one of the higher numbered bit-flags might be layout order).  The debug layout command is mostly handled in the init.lua file, if you want to take a look.

I'll have some time this weekend and will also do some more digging and see what I can come up with.

**Comment by szymonkaliski** [comment]
Thanks for the pointers, reproducing it is quite easy, run `hs.screen():spaces()`, reorder some spaces, and run it again, results stay the same, even though the spaces have moved :)

**Comment by asmagill** [comment]
See latest updates.

**Comment by szymonkaliski** [comment]
:+1: perfect, thanks!

**Comment by szymonkaliski** [comment]
btw, if you're curious, here's how I use it right now: https://github.com/szymonkaliski/Dotfiles/blob/ae42c100a56c26bc65f6e3ca2ad36e30b558ba10/Dotfiles/hammerspoon/utils/spaces/dots.lua :)

**Comment by asmagill** [comment]
nice... I may incorporate a variant of this myself into my configuration :-)

**Comment by jdtsmith** [comment]
Has this been corrected in recent versions?  I get out of order results for hs.screen:spaces() after rearranging spaces.  Trying to use some Dock accessibility to remove the current fullscreen space, and to match accessibility object to space I need to know the layout.  Just like the OP, I find that rearranging spaces doesn't change the reported order.

**Comment by jdtsmith** [comment]
As a followup, I find that `spaces:layout()` _does_ report in the correct order, so I've switched to that (indexed by the screen UUID).
