### ISSUE TITLE
Problem with spaces.layout()

### ISSUE THREAD

**Issue by sjthespian** [asmagill/hs._asm.undocumented.spaces#10]
I would swear this was working when I first started playing with hammerspoon, but now I'm having issues with some of the spaces methods. The biggest problem is with layout(). It is return an empty table while spaces.query() is working fine.

As an example, here is what I see in the hammerspoon console running with 6 spaces and two displays:

```
> for k,v in ipairs(spaces.layout()) do
  print(k)
end


> for k,v in ipairs(spaces.query()) do
  print(k)
end
1
2
3
4
5
6


> for k,v in ipairs(spaces.query()) do
  print(v)
end
241
6
5
4
3
1
```

**Comment by asmagill** [comment]
The layout function groups the spaces by monitor ID, so you need to grab those keys first, even when you just have one monitor:

~~~lua
for screen, layout in pairs(spaces.layout()) do
    print("Monitor:", screen)
    for k, v in ipairs(layout) do print(v) end
end
~~~
