### ISSUE TITLE
Can't remove spaces

### ISSUE THREAD

**Issue by dabrady** [asmagill/hs._asm.undocumented.spaces#14]
All my attempts to use `spaces.removeSpace` have failed to remove the space in question.

Environment: 
- macOS Sierra 10.12.6
- "Displays have separate spaces" is OFF, though I've also tried with it on (didn't work)
- single screen

Using `spaces.query(spaces.masks.allSpaces)` to obtain the ids of all existing spaces, I have attempted to delete them using `spaces.removeSpace`, with the `resetDock` parameter set to true as well as false, using something like this:
```lua
-- Remove all other spaces
local allSpaces = spaces.query(spaces.masks.allSpaces)
local activeSpace = spaces.activeSpace()
for _,spaceId in ipairs(allSpaces) do
  if spaceId ~= activeSpace then
    spaces.removeSpace(spaceId) -- tried setting the optional second parameter to true and false
  end
end
```
The only thing `spaces.removeSpace` does in my case is move all windows from the space I'm trying to remove to the active space: the space itself is not removed.

---
I was going to include some debug info from `spaces.debug`, but only `spaces.debug.layout` works for me: the others crash Hammerspoon. Here is a screenshot of a simple console example that provides evidence of the non-removal behavior I'm seeing:
<img width="407" alt="screen shot 2018-01-06 at 13 30 09" src="https://user-images.githubusercontent.com/2475919/34642724-f4a90270-f2e5-11e7-982d-9395c37d99ea.png">
I should like to note that `spaces.createSpace` works just fine for me: it's only their removal that is unsuccessful.

**Comment by jdtsmith** [comment]
I find the same in Mojave 10.14.  No ability to `spaces.removeSpace`.  The space does seem to be deleted from the internal register of spaces, since deleting it again results in an error.

**Comment by sharpobject** [comment]
Confirming that spaces.removeSpace does not work on Mac OS 11.1.

**Comment by asmagill** [comment]
This module is no longer being maintained and will be archived soon. You should check out https://github.com/asmagill/hs._asm.spaces which will (hopefully) soon be added to Hammerspoon itself as `hs.spaces`.

If you do decide to try out the newer version, please let me know if the problem persists and post an issue there so I can look into more closely.

Thanks!
