### ISSUE TITLE
`createSpace` on other screen

### ISSUE THREAD

**Issue by jdtsmith** [asmagill/hs._asm.undocumented.spaces#15]
> NOTE: This isn't currently working correctly with multi-monitor setups under OS X 10.11 -- no matter which UUID you provide, it only creates new spaces on the currently active display. I would appreciate any feedback for 10.10 or earlier. I hope to have a fix or work-around soon.

Any progress on this for >=10.10?  Still the case on 10.14, and haven't come up with a workaround...

**Comment by deszip** [comment]
On Monterey struggling with the same issue, maybe change somehow the active display, add space and then change it back?

**Comment by asmagill** [comment]
This module is no longer being maintained and will be archived soon. You should check out https://github.com/asmagill/hs._asm.spaces which will (hopefully) soon be added to Hammerspoon itself as `hs.spaces`.

If you do decide to try out the newer version, please let me know if the problem persists and post an issue there so I can look into more closely.

Thanks!
