### ISSUE TITLE
Support for App Expose on Catalina?

### ISSUE THREAD

**Issue by vlad-cotfas** [asmagill/hs._asm.undocumented.spaces#17]
Is there any support to check also when the App Expose is active? I`m not able to make it work to see when the app expose is active. :(

**Comment by asmagill** [comment]
As of right now, no, I know of no way to determine when Expose is active, either with this module or another.

**Comment by asmagill** [comment]
Actually, the next version of Hammerspoon will be able to detect App Expose with a new module, `hs.axuielement`. It works by checking what accessibility elements currently exist for the Dock application. I'm not sure if the specific functions in my example file will be added to a module at some point, but the required support in Hamemrspoon should be in the next release.

See https://github.com/asmagill/hs._asm.axuielement/blob/master/examples/dockStuff.lua#L79-L93
