### ISSUE TITLE
spaces.changeToSpace animation?

### ISSUE THREAD

**Issue by szymonkaliski** [asmagill/hs._asm.undocumented.spaces#2]
Is there any way I could get the spaces to animate when using `changeToSpace`?

**Comment by asmagill** [comment]
Not directly.  Check out the documentation on Raw access to the spaces api, if you want to attempt to roll your own with the transform function, but if you just want the default animation, you're better off trying one of the methods which use hs.eventtap to simulate the typing of the ctrl-# and ctrl-left/ctrl-right keystrokes and trigger the system space change routines that way.

https://github.com/Hammerspoon/hammerspoon/issues/235 and https://github.com/Hammerspoon/hammerspoon/issues/581 discuss some examples of doing this and some of the things you'll need to be aware of/work around.

**Comment by szymonkaliski** [comment]
Thanks for the info! Could you point me in the right direction about using transform function for DIY solution?

**Comment by asmagill** [comment]
Check out the examples directory in the repository.  Also added a link to Apple's CGAffineTransform documentation in the RawAccess.md file.  Added a function (not strictly necessary, but the example does use it to toggle the animation state), so you may also want to grab or compile the latest release.

**Comment by szymonkaliski** [comment]
Thanks, this is awesome! :)
