### ISSUE TITLE
spaces.activeSpace() returns focused space not primary screen space in mulit monitor setup

### ISSUE THREAD

**Issue by Tylerc230** [asmagill/hs._asm.undocumented.spaces#20]
The docs for spaces.activeSpace() state: "In a multi-monitor setup, this will return the ID of the active space on the primary screen." My observation is that it returns the space of the focused screen (ie the screen where the focused window resides). To test I print out the number returned by this method. It prints a different number depending on the screen containing the focused window.

**Comment by asmagill** [comment]
This module is no longer being maintained and will be archived soon. You should check out https://github.com/asmagill/hs._asm.spaces which will (hopefully) soon be added to Hammerspoon itself as `hs.spaces`.

If you do decide to try out the newer version, please let me know if the problem persists and post an issue there so I can look into more closely.

Thanks!
