### ISSUE TITLE
"module 'LuaSkin' not found" on M1

### ISSUE THREAD

**Issue by hanvari** [asmagill/hs._asm.undocumented.spaces#23]
Hello,

I've been using this module for a long time now on an intel MBP. 
I've just upgraded to a new M1 Pro MBP and noticed the same release I've been using is not compatible and there is no release available targeting M1 (arm64).
So I tried to compile the module from the source. But I get this error: "module 'LuaSkin' not found"

Any suggestions?

**Comment by mikedmcfarland** [comment]
@hanvari it was happenstance for me to see that there is a zip with the universal build [in the repo itself](https://github.com/asmagill/hs._asm.undocumented.spaces/blob/master/spaces-v0.2.1.1-universal.tar.gz).
I downloaded it, installed it in `~/.hammerspoon/hs` and things are working on my M1.
I encountered the exact error when trying to build it, but in reality I just want the universal release anyway.
Hope that helps.

**Comment by asmagill** [comment]
This module is no longer being maintained and will be archived soon. You should check out https://github.com/asmagill/hs._asm.spaces which will (hopefully) soon be added to Hammerspoon itself as `hs.spaces`.

If you do decide to try out the newer version, please let me know if the problem persists and post an issue there so I can look into more closely.

Thanks!
