### ISSUE TITLE
Is it possible to get the space "name" rather then ID?

### ISSUE THREAD

**Issue by dmitrym0** [asmagill/hs._asm.undocumented.spaces#25]
Hey folks,

I'm trying to get the space shown when I switch around:

```
_spaces = require("hs._asm.undocumented.spaces")
hs.spaces.watcher.new(function(space) hs.alert.show("Space " .. _spaces.activeSpace()) end):start()
```

..but this seems to display the space ID -- the first space is "1", the second space (to the right) is somehow "668". How can I get the second space to show "2"?

Thanks

**Comment by bviefhues** [comment]
You can iterate over `spaces.layout()[screen]`. That returns an ordered list of spaces which can be enumerated through `ipairs()`.

**Comment by dmitrym0** [comment]
Sorry if I'm being dense:

```
> _spaces = require("hs._asm.undocumented.spaces")
2022-02-28 20:16:22: -- Loading extension: task
2022-02-28 20:16:22: -- Loading extension: console

> _spaces.layout()
table: 0x600000f10d80

> #_spaces.layout()
0
```

So looks like `layout()` is empty?

On the other hand `_spaces.currentSpace()` does exactly what I want. I'm surprised that `_spaces.layout()` is empty.

**Comment by asmagill** [comment]
This module is no longer being maintained and will be archived soon. You should check out https://github.com/asmagill/hs._asm.spaces which will (hopefully) soon be added to Hammerspoon itself as `hs.spaces`.

If you do decide to try out the newer version, please let me know if the problem persists and post an issue there so I can look into more closely.

Thanks!
