### ISSUE TITLE
`spaces.moveWindowToSpace` stopped working on Monterey 12.2.1

### ISSUE THREAD

**Issue by dgurkaynak** [asmagill/hs._asm.undocumented.spaces#26]
Hey, thanks for this great library! You've already noted in the readme that its may not function as intended on future versions of macOS. And I guess it's just happened for me. With macOS Monterey 12.2.1 update, `spaces.moveWindowToSpace` API (along with `hs.window:spacesMoveTo`) stopped working for me. `spaces.activeSpace()` is still returning spaceID correctly, but when I try to move a window to another space, it has no effect.

**Comment by JayFarei** [comment]
I have the same issue. A visual glitch showing the target wallpaper when the method is invoked but as you say - when I try to move a window it has no effect.

**Comment by asmagill** [comment]
This module is no longer being maintained and will be archived soon. You should check out https://github.com/asmagill/hs._asm.spaces which will (hopefully) soon be added to Hammerspoon itself as `hs.spaces`.

If you do decide to try out the newer version, please let me know if the problem persists and post an issue there so I can look into more closely.

Thanks!
