### ISSUE TITLE
`spaces.changeToSpace` stopped working on Monterey 12.2.1

### ISSUE THREAD

**Issue by sharpobject** [asmagill/hs._asm.undocumented.spaces#27]
When using changeToSpace I somehow take all the windows with me. I wanted to leave them behind!

**Comment by asmagill** [comment]
This module is no longer being maintained and will be archived soon. You should check out https://github.com/asmagill/hs._asm.spaces which will (hopefully) soon be added to Hammerspoon itself as `hs.spaces`.

If you do decide to try out the newer version, please let me know if the problem persists and post an issue there so I can look into more closely.

Thanks!
