### ISSUE TITLE
guard against moving a window to its own space

### ISSUE THREAD

**Issue by yoavg** [asmagill/hs._asm.undocumented.spaces#3]
First, I'd like to say huge thanks for the spaces module. It is very useful.

Now, a small bug: when moving a window to the space it is currently on, the window is lost (it disappears from all spaces, and I can't figure out how to make it visible again).

It would be useful to guard against this at the module level.

**Comment by asmagill** [comment]
good catch... I know what's going on and its a relatively simple fix... I'll get it in later today.

**Comment by asmagill** [comment]
see latest release

**Comment by yoavg** [comment]
Wow, that was quick! super. thanks.
