### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by cabrinha** [asmagill/hs._asm.undocumented.spaces#4]
```
[ yuppie@athena ~/.hammerspoon ]$ git clone https://github.com/asmagill/hs._asm.undocumented.spaces spaces
Cloning into 'spaces'...
remote: Counting objects: 44, done.
remote: Total 44 (delta 0), reused 0 (delta 0), pack-reused 44
Unpacking objects: 100% (44/44), done.
Checking connectivity... done.
[ yuppie@athena ~/.hammerspoon ]$ cd spaces/
[ yuppie@athena ~/.hammerspoon/spaces ]$ HS_APPLICATION=/Applications
[ yuppie@athena ~/.hammerspoon/spaces ]$ PREFIX=~/.hammerspoon
[ yuppie@athena ~/.hammerspoon/spaces ]$ make install
luac-5.3 -p init.lua && echo "Passed"
/bin/sh: luac-5.3: command not found
make: *** [verify] Error 127
```

**Comment by asmagill** [comment]
The make file template I generally use does a check with the lua compiler to do a syntax check.  I've installed lua with brew, and that's what its looking for.

You can take this check out by changing line 33 of the Makefile from:

``` make
all: verify $(SOFILE)
```

to:

``` make
all: $(SOFILE)
```

I will update the repository to take this out as well -- by the time I've uploaded changes to this repository, it's a pretty safe bet that I've done the syntax check myself already :-)

**Comment by cabrinha** [comment]
Same error, even with line 33 changed:

```
luac-5.3 -p init.lua && echo "Passed"
/bin/sh: luac-5.3: command not found
make: *** [verify] Error 127
```

I have lua installed through homebrew as well.

```
[ yuppie@athena ~/.hammerspoon/spaces ]$ brew list | grep lua
lua
luajit
```

**Comment by asmagill** [comment]
My bad, for some reason I thought brew had moved to lua53 being the default.  Because Hammerspoon has moved to lua53 as the embedded version, to include the check, you need lua53, which can be installed as well without interfering with lua (which is 5.2 by default in brew).

You may need to add the versions tap, if you wish to install lua53... I think this will do it:

``` sh
$ brew tap homebrew/versions
$ brew install lua53
```

**Comment by cabrinha** [comment]
Thanks man! Looks like that worked.
