### ISSUE TITLE
changeToSpace causes reloading of desktop / dock

### ISSUE THREAD

**Issue by yoavg** [asmagill/hs._asm.undocumented.spaces#6]
Sorry for flooding with these issues -- I am so excited about hammerspoon and this module that I am trying many things :)

There is some small lag when calling changeToSpace, and the desktop background is reloaded (I assume this is the resetting of the dock, right?)

However, when using the mission control switcher, or TotalSpaces2 switcher, this behavior does not happen.

Is using these programs the same as using the legacy moveToSpace (or not restarting the dock), or are they doing something different?

**Comment by asmagill** [comment]
I would love to know how they're doing it!

The only way I could discover to get space changes to become truly active for the user is by resetting the Dock... the Dock is what manages the spaces, so when it is reset, it appears to do a scan of the current setup and then makes sure that what is configured matches what the user can move to/use.

Without the Dock reset, creating/removing a space does affect the spaces -- you can see this by checking the results of the query function -- but you can't actually move to a new space through trackpad gestures/ctrl-keys or see it in Mission Control, and a removed space still appears in Mission Control.

Likewise, changing to a space works, but without the Dock reset, if you change spaces by any other method afterwards, it first jumps you back to your previous space and you move from it's position in the "order of spaces", not the position that was just visible to you.

This has led me to believe that either our app needs certain entitlements (but I have no idea which ones or how to add/request them) to allow it to communicate with the WindowServer with the same authority as the Dock, or that we need a way to tell the Dock to do a rescan without actually restarting, but so far, I haven't been able to find out how to do either, or even if my guess are even close to correct!

I may take a look at TotalSpaces2 sometime and see if there is a way to monitor what its doing through the notification center... I doubt it, or more people would know how by now, but if they've truly figured it out, it may be worth a shot.

**Comment by yoavg** [comment]
Interesting. Pitty Apple do not expose a proper API for the virtual desktops :(
Unfortunately I will probably be of no use in helping to resolve this in the near future, as I really have zero experience in the OSX environment, let alone in low-level OSX stuff. But just a quick question based on my experience in other platforms a long time ago: is there a way to track low level calls made by an OSX application? my intuition is that the Dock is calling some special API to do the space handling, and if you can find out what it is, you could just call it instead of restarting the entire process.

fwiw, the TotalSpaces2 page state that they do some code injection, which is the reason why you need to disable some security feature in El Capitan for it to work.

**Comment by asmagill** [comment]
I am closing this because I have not discovered anything new thus far which would change my understanding of the problem and will not have the time to look into it further in the foreseeable future; reopen if anyone can provide more information or suggestions on a better fix.

**Comment by asmagill** [comment]
In case I ever want to revisit this, https://github.com/koekeishiya/yabai/ seems to be able to work more directly with spaces by utilizing a script extension injected into the Dock. This requires disabling SIP (at least temporarily) and root/sudo (again, at least temporarily) both things we have studiously avoided in Hammerspoon, but it's a start if this ever becomes important enough to revisit again.
