### ISSUE TITLE
CGSCopySpaces order

### ISSUE THREAD

**Issue by kasper** [asmagill/hs._asm.undocumented.spaces#8]
Hi, thank you for this resource! This question is not directly related to this project, but I was wondering if you would have any insight. I’ve been hacking around with the private APIs and I’m puzzled about if you can get a list of the spaces in the order the user has them sorted in Mission Control. `CGSCopySpaces(…)` seems to return the IDs only in the creation order. Do you know any solution for this?

**Comment by szymonkaliski** [comment]
look here: https://github.com/asmagill/hs._asm.undocumented.spaces/issues/1 :)

**Comment by kasper** [comment]
@szymonkaliski Ah, great! I was searching from the wrong place. Thanks!
